### ISSUE TITLE
Use of horizontal and vertical confusing

### ISSUE THREAD

**Issue by TxHawks** [inuitcss/trumps.spacing#12]
To my mind, the horizontal padding is that which is applied at the top and bottom of a box, since they are, well, horizontal...

I get that they are along the vertical axis of the box, but so are the top and bottom borders, and you wouldn't call a border at the top of a box a vertical border...

Just think of what the horizon is - the precieved bottom of the skies.

**Comment by nenadjelovac** [comment]
@TxHawks 

You got me all confused for a few minutes there :) 

>To my mind,

I think this might be the key ;)

Try to think of it like this:
Border is an object, margin (padding) is [force](https://www.google.rs/search?q=force&oq=force&aqs=chrome..69i57j0l5.655j0j1&sourceid=chrome&ie=UTF-8). 

Horizontal border is an object which sits parallel to horizon plane.
When you pull/push something to the left or right, you are moving it (horizontally) on the horizontal plane, not vertical. Thus such margin/padding is called horizontal margin/padding.

Hope it helps.

**Comment by nenadjelovac** [comment]
@TxHawks any comments on this? :) If not I'd close this issue.

thank you

**Comment by florianbouvot** [comment]
@nenadjelovac like you, a little confused at first reading. When I think about top and bottom spacing this match the vertical rhythm : so no problem ;)

**Comment by TxHawks** [comment]
You are correct, `to my mind` was the key...

Thanks for clearing that up

**Comment by nenadjelovac** [comment]
@TxHawks no problems ;)

@florianbouvot +1
