### ISSUE TITLE
Suggestion for spacing naming

### ISSUE THREAD

**Issue by BenjaminRCooper** [inuitcss/trumps.spacing#13]
Due to all spacing based around a base-spacing-unit, what are your thoughts on using something a little more readable than `--` and `++`?

I have a similar approach in an internal library, and I use something like so:

`pad-t-2x` & `pad-t-1/2`.

Very minimal, but as I say just a suggestion as I find it a little more readable.

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this topic is still relevant to you, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks for your time and your effort.
