### ISSUE TITLE
Why use `--` or `++` instead of size names?

### ISSUE THREAD

**Issue by renatocarvalho** [inuitcss/trumps.spacing#2]
Hey there Harry, I was wondering why you chose to use symbols like `--` or `++` to specify the sizes instead names like `tiny` or `huge`. I found a bit confusing and since we use names on other places for the sizes.

What do you think on changing those to semantic names?

**Comment by florianbouvot** [comment]
I agree with @csshugs, short name are very useful for this utilities (faster than inuit v5 naming convention) unlike objects and components name need to be more verbose.

**Comment by csswizardry** [comment]
The idea behind `--` and `++` is to imply ‘a bit less’ or ‘a bit more’.

Most frameworks use things like `.p10` for `padding: 10px;`, whereas inuitcss tries to be less literal and prescriptive and allows you to think and work in terms of adjustments: _I want this padding a little bit bigger._

I’m going to close this off for now. I want inuitcss’ spacing to always feel that rapid; typing at the speed of thought.

Thanks,
H

**Comment by ArmorDarks** [comment]
There is one more great argument in defense of `++` and `--` idea which I've never heard for some reason.

How would you name, for exmaple, `mb---`? Or `mb----`, or `pd++++`?

Those abstract `-` and `+` have good balance of obviousness and usability and doesn't require to think about "how to name that extra little padding — super-tiny, or what?"
