### ISSUE TITLE
Can't extend classes with + or - signs

### ISSUE THREAD

**Issue by trenkwill** [inuitcss/trumps.spacing#4]
Hi Harry,

Extending the regular class: @extend .pt; works
but when I try with @extend .pt+; I get this error:

"Error: Can't extend .pt +: can't extend nested selectors\A on line 1063 of webroot/styles/main.scss"

Any ideas ?
Thanks !

**Comment by csshugs** [comment]
The `+` character is css syntax (sibling selector). Therefore you got to escape it by:

```css
@extend .pt\+;
```

**Comment by trenkwill** [comment]
That makes sense, thank you !

**Comment by HarleyKwyn** [comment]
This also breaks jade. I can use (class="pt+") but it's kind of obnoxious, for now just rolling with my own using the push--large and similar classes.

**Comment by nenadjelovac** [comment]
@trenkwill 

> Extending the regular class: @extend .pt; works

Why would you ever extend it? Better use `padding-top: $inuit-spacing-unit`.

Also, know [when](http://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/) to use extend, and try to [avoid it](http://www.sitepoint.com/avoid-sass-extend/) as much as possible.
