### ISSUE TITLE
Missing the option to alter tiny, small, large and huge margins/paddings.

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/trumps.spacing#5]
E.g. 

```

$inuit-margin--tiny:     quarter($inuit-margin) !default;
$inuit-margin--small:      halve($inuit-margin) !default;
$inuit-margin--large:     double($inuit-margin) !default;
$inuit-margin--huge:   quadruple($inuit-margin) !default;

$inuit-padding--tiny:     quarter($inuit-padding) !default;
$inuit-padding--small:      halve($inuit-padding) !default;
$inuit-padding--large:     double($inuit-padding) !default;
$inuit-padding--huge:   quadruple($inuit-padding) !default;

```

**Comment by Crawleyprint** [comment]
+1 for this

**Comment by Crawleyprint** [comment]
There is another bug if you're using rems as base units - resulting numbers are rounded, which is undesirable most of the time. Using !default with paddings and margins would be acceptable soution for this, as well.

**Comment by csswizardry** [comment]
Interesting.

As inuitcss has a baseline grid by default, I’d decided to force spacing to keep on it. I guess it would be more consistent to make it configurable though.

Anyone fancy doing this? (Including the Bower and npm versions and tags etc. ;))

**Comment by Crawleyprint** [comment]
I can start, and @nenadjelovac could jump in if needed. Never did the whole package before :D

**Comment by florianbouvot** [comment]
I always follow baseline grid but I think it make sense because others inuit's modules offers this possibility.

**Comment by csswizardry** [comment]
> because others inuit's modules offers this possibility.

I’m wondering if we should strip that kind of stuff out. On the one hand, it makes things incredibly flexible and configurable, but on the other hand it adds a lot of overhead and verbosity.

I’m not wanting to open up a full-scale discussion here, so no need to even respond, but I just thought I’d share what I’ve been wondering about :)

**Comment by nenadjelovac** [comment]
> I’m wondering if we should strip that kind of stuff out. 

NO :D It really is helpful. 

I've done (or been a part of) ~20 projects that used inuitcss and having those stuff as an option was a huge plus. Not every project needed that, though. 

Let's say 15 projects did not need it, but the remaining that did would be a lot dirtier if there were no config ;)
